// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SigortaApp.Data;

#nullable disable

namespace SigortaApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.31");

            modelBuilder.Entity("SigortaApp.Models.AileBireyi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DogumTarihi")
                        .HasColumnType("TEXT");

                    b.Property<int>("PoliceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TcKimlikNo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Yakinlik")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PoliceId");

                    b.ToTable("AileBireyleri");
                });

            modelBuilder.Entity("SigortaApp.Models.Ayar", b =>
                {
                    b.Property<string>("Anahtar")
                        .HasColumnType("TEXT");

                    b.Property<string>("Deger")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Anahtar");

                    b.ToTable("Ayarlar");
                });

            modelBuilder.Entity("SigortaApp.Models.Hasar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Durum")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("HasarTarihi")
                        .HasColumnType("TEXT");

                    b.Property<int>("PoliceId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Tutar")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PoliceId");

                    b.ToTable("Hasarlar");
                });

            modelBuilder.Entity("SigortaApp.Models.KisaDonemOrani", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxGun")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PrimOrani")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MaxGun")
                        .IsUnique();

                    b.ToTable("KisaDonemOranlari");
                });

            modelBuilder.Entity("SigortaApp.Models.Musteri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Adres")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DogumTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Silindi")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TcKimlikNo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TcKimlikNo")
                        .IsUnique();

                    b.ToTable("Musteriler");
                });

            modelBuilder.Entity("SigortaApp.Models.Police", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BaslangicTarihi")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("BitisTarihi")
                        .HasColumnType("TEXT");

                    b.Property<int>("Durum")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("IadeTutari")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int?>("IptalHesapYontemi")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IptalNedeni")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("IptalTarihi")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("KazanilanPrim")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("MusteriId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("NetPrim")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int?>("OncekiPoliceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PoliceNo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Prim")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TanzimTarihi")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UrunId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("VergiTutari")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MusteriId");

                    b.HasIndex("PoliceNo")
                        .IsUnique();

                    b.HasIndex("UrunId");

                    b.ToTable("Policeler");
                });

            modelBuilder.Entity("SigortaApp.Models.PoliceTeminati", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Aktif")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BeklemeSuresiGun")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CikarilmaTarihi")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EklenmeTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Istisnalar")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("KatilimPayiOrani")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Limit")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("PoliceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TeminatAdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TeminatId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PoliceId");

                    b.HasIndex("TeminatId");

                    b.ToTable("PoliceTeminatlari");
                });

            modelBuilder.Entity("SigortaApp.Models.TarifeSatiri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("GecerliBaslangic")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("GecerliBitis")
                        .HasColumnType("TEXT");

                    b.Property<int>("Grup")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UrunId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("YasMax")
                        .HasColumnType("INTEGER");

                    b.Property<int>("YasMin")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("YillikPrim")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UrunId");

                    b.ToTable("Tarifeler");
                });

            modelBuilder.Entity("SigortaApp.Models.Teminat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aciklama")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Kod")
                        .IsUnique();

                    b.ToTable("Teminatlar");
                });

            modelBuilder.Entity("SigortaApp.Models.Urun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aciklama")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Aktif")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Tur")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Kod")
                        .IsUnique();

                    b.ToTable("Urunler");
                });

            modelBuilder.Entity("SigortaApp.Models.UrunTeminati", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BeklemeSuresiGun")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Istisnalar")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("KatilimPayiOrani")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Limit")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("TeminatId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UrunId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TeminatId");

                    b.HasIndex("UrunId", "TeminatId")
                        .IsUnique();

                    b.ToTable("UrunTeminatlari");
                });

            modelBuilder.Entity("SigortaApp.Models.VergiParametresi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Aktif")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("GecerliBaslangic")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Oran")
                        .HasPrecision(9, 4)
                        .HasColumnType("TEXT");

                    b.Property<int?>("UrunId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Vergiler");
                });

            modelBuilder.Entity("SigortaApp.Models.Zeyil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("TEXT");

                    b.Property<int>("PoliceId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PrimFarki")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("Tur")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("YururlukTarihi")
                        .HasColumnType("TEXT");

                    b.Property<int>("ZeyilNo")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PoliceId", "ZeyilNo")
                        .IsUnique();

                    b.ToTable("Zeyiller");
                });

            modelBuilder.Entity("SigortaApp.Models.AileBireyi", b =>
                {
                    b.HasOne("SigortaApp.Models.Police", "Police")
                        .WithMany("AileBireyleri")
                        .HasForeignKey("PoliceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Police");
                });

            modelBuilder.Entity("SigortaApp.Models.Hasar", b =>
                {
                    b.HasOne("SigortaApp.Models.Police", "Police")
                        .WithMany("Hasarlar")
                        .HasForeignKey("PoliceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Police");
                });

            modelBuilder.Entity("SigortaApp.Models.Police", b =>
                {
                    b.HasOne("SigortaApp.Models.Musteri", "Musteri")
                        .WithMany("Policeler")
                        .HasForeignKey("MusteriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SigortaApp.Models.Urun", "Urun")
                        .WithMany()
                        .HasForeignKey("UrunId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Musteri");

                    b.Navigation("Urun");
                });

            modelBuilder.Entity("SigortaApp.Models.PoliceTeminati", b =>
                {
                    b.HasOne("SigortaApp.Models.Police", "Police")
                        .WithMany("Teminatlar")
                        .HasForeignKey("PoliceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SigortaApp.Models.Teminat", "Teminat")
                        .WithMany()
                        .HasForeignKey("TeminatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Police");

                    b.Navigation("Teminat");
                });

            modelBuilder.Entity("SigortaApp.Models.TarifeSatiri", b =>
                {
                    b.HasOne("SigortaApp.Models.Urun", "Urun")
                        .WithMany("Tarifeler")
                        .HasForeignKey("UrunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Urun");
                });

            modelBuilder.Entity("SigortaApp.Models.UrunTeminati", b =>
                {
                    b.HasOne("SigortaApp.Models.Teminat", "Teminat")
                        .WithMany()
                        .HasForeignKey("TeminatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SigortaApp.Models.Urun", "Urun")
                        .WithMany("Teminatlar")
                        .HasForeignKey("UrunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Teminat");

                    b.Navigation("Urun");
                });

            modelBuilder.Entity("SigortaApp.Models.Zeyil", b =>
                {
                    b.HasOne("SigortaApp.Models.Police", "Police")
                        .WithMany("Zeyiller")
                        .HasForeignKey("PoliceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Police");
                });

            modelBuilder.Entity("SigortaApp.Models.Musteri", b =>
                {
                    b.Navigation("Policeler");
                });

            modelBuilder.Entity("SigortaApp.Models.Police", b =>
                {
                    b.Navigation("AileBireyleri");

                    b.Navigation("Hasarlar");

                    b.Navigation("Teminatlar");

                    b.Navigation("Zeyiller");
                });

            modelBuilder.Entity("SigortaApp.Models.Urun", b =>
                {
                    b.Navigation("Tarifeler");

                    b.Navigation("Teminatlar");
                });
#pragma warning restore 612, 618
        }
    }
}
